CREATE DATABASE VENTAS
USE VENTAS

CREATE TABLE PRODUCTOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
CODIGO CHAR(6) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
MARCA VARCHAR(50) NOT NULL,
MODELO VARCHAR(50) NOT NULL,
PRECIO DOUBLE NOT NULL,
CANTIDAD INT NOT NULL
)

SELECT * FROM productos

CREATE TABLE EMPLEADOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
CODIGO CHAR(6) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
DISTRITO VARCHAR(50) NOT NULL,
EDAD INT NOT NULL,
DNI CHAR(8) NOT NULL,
GÉNERO CHAR(1) NOT NULL,
TURNO VARCHAR(50) NOT NULL,
MODALIDAD VARCHAR(50) NOT NULL
)

CREATE TABLE CLIENTES(
ID INT AUTO_INCREMENT PRIMARY KEY,
DESCRIPCIÓN VARCHAR(50) NOT NULL,
DIRECCIÓN VARCHAR(50) NOT NULL,
TELÉFONO VARCHAR(50) NOT NULL,
RUC CHAR(11) NOT null
)

CREATE TABLE PROVEEDORES(
ID INT AUTO_INCREMENT PRIMARY KEY,
DESCRIPCIÓN VARCHAR(50) NOT NULL,
DIRECCIÓN VARCHAR(50) NOT NULL,
TELÉFONO VARCHAR(50) NOT NULL
)
